image: 192.168.16.36:5000/cicd

stages:
  - lint
  - test
  - build
  - deploy

lint:
  before_script:
    - pyenv local 3.7.6
    - python -V
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
  stage: lint
  script:
    - pip install -e .[dev]
    - pre-commit run -a
    - invoke lint-commit
  tags:
    - docker
    - local

test:
  before_script:
    - pyenv local 3.6.7 3.7.6 3.8.7
    - python -V
  stage: test
  script:
    - tox
  tags:
    - docker
    - local

build_docs:
  before_script:
    - pyenv local 3.7.6
  stage: build
  script:
    - tox -e docs
  artifacts:
    paths:
      - docs/_build
    expire_in: 3 day
  tags:
    - docker
    - local
  only:
    - tags

build_repo:
  image: 192.168.16.36:5000/manylinux1_x86_64
  stage: build
  variables:
    PYPI_INDEX: http://192.168.16.34:3141/rrlibrary/dev/
    TRUSTED_HOST: 192.168.16.34
  script:
    - for PIP in /opt/python/cp3{6..8}*/bin/pip; do ${PIP} install Cython -i ${PYPI_INDEX} --trusted-host=${TRUSTED_HOST}; done
    - for PYTHON in /opt/python/cp3{6..8}*/bin/python; do ${PYTHON} setup.py bdist_wheel; done
    - for WHL in dist/*.whl; do auditwheel repair ${WHL} -w wheelhouse; done
  artifacts:
    paths:
      - wheelhouse
    expire_in: 3 day
  tags:
    - docker
    - local
  only:
    - tags

deploy:
  before_script:
    - pyenv local 3.7.6
  stage: deploy
  script:
    - pip install twine
    - pip install cython
    - twine upload wheelhouse/*.whl -r devpi
    - python setup.py upload_docs --upload-dir docs/_build -r devpi
  dependencies:
    - build_repo
    - build_docs
  tags:
      - docker
      - local
  only:
    - tags
